import {
  CODEPUSH_PRODUCTION_DEPLOYMENT_KEY,
  CODEPUSH_STAGING_DEPLOYMENT_KEY,
} from '@env';

export const STAGING_DEPLOYMENT_KEY = CODEPUSH_STAGING_DEPLOYMENT_KEY;
export const PRODUCTION_DEPLOYMENT_KEY = CODEPUSH_PRODUCTION_DEPLOYMENT_KEY;

export const FORCE_STAGING = false;
